namespace MarkItDown;

/// <summary>
/// Common metadata key constants used throughout conversion and intelligence providers.
/// </summary>
public static class MetadataKeys
{
    public const string Width = "width";
    public const string Height = "height";
    public const string Unit = "unit";
    public const string Page = "page";
    public const string RowCount = "rowCount";
    public const string ColumnCount = "columnCount";
    public const string Caption = "caption";
    public const string TableIndex = "tableIndex";
    public const string TablePageStart = "table.pageStart";
    public const string TablePageEnd = "table.pageEnd";
    public const string TablePageRange = "table.pageRange";
    public const string TableComment = "table.comment";
    public const string ConverterDurationMs = "converter.durationMs";
    public const string Provider = "provider";
    public const string ModelVersion = "modelVersion";
    public const string DocumentIntelligenceProvider = "documentIntelligence.provider";
    public const string Slide = "slide";
    public const string OcrText = "ocrText";
    public const string VideoId = "videoId";
    public const string Language = "language";
    public const string Segment = "segment";
    public const string TotalDuration = "totalDuration";
    public const string Confidence = "confidence";
    public const string SafeSearchAdult = "safeSearch.adult";
    public const string SafeSearchMedical = "safeSearch.medical";
    public const string SafeSearchRacy = "safeSearch.racy";
    public const string SafeSearchViolence = "safeSearch.violence";
    public const string Snapshot = "snapshot";
    public const string Channel = "channel";
    public const string ChannelUrl = "channelUrl";
    public const string ViewCount = "viewCount";
    public const string LikeCount = "likeCount";
    public const string Duration = "duration";
    public const string UploadDate = "uploadDate";
    public const string Tags = "tags";
    public const string IsAutoGenerated = "autoGenerated";
    public const string DetailedDescription = "detailedDescription";
    public const string DataTableMarkdown = "dataTableMarkdown";
    public const string MermaidDiagram = "mermaid";
    public const string ImageEnriched = "imageEnriched";
    public const string AsciiArt = "asciiArt";
    public const string FullMarkdown = "fullMarkdown";
    public const string ArtifactPath = "artifact.path";
    public const string ArtifactFileName = "artifact.fileName";
    public const string ArtifactRelativePath = "artifact.relativePath";
    public const string WorkspaceDirectory = "workspace.directory";
    public const string WorkspaceSourceFile = "workspace.sourceFile";
    public const string WorkspaceMarkdownFile = "workspace.markdownFile";
    public const string LayoutRegions = "layoutRegions";
    public const string ImageInsight = "imageInsight";
    public const string EmailAttachmentsCount = "email.attachments.count";
    public const string EmailAttachments = "email.attachments";
    public const string NotebookCellsCount = "notebook.cells.count";
    public const string NotebookCellsMarkdown = "notebook.cells.markdown";
    public const string NotebookCellsCode = "notebook.cells.code";
    public const string NotebookCellsRaw = "notebook.cells.raw";
    public const string NotebookMetadataTitle = "notebook.metadata.title";
    public const string NotebookMetadataAuthors = "notebook.metadata.authors";
    public const string NotebookMetadataKernel = "notebook.metadata.kernel";
    public const string NotebookMetadataLanguage = "notebook.metadata.language";
    public const string NotebookCellIndex = "notebook.cell.index";
    public const string NotebookCellLabel = "notebook.cell.label";
    public const string NotebookCellType = "notebook.cell.type";
    public const string EpubSection = "epub.section";
    public const string EpubTitle = "epub.title";
    public const string EpubAuthor = "epub.author";
    public const string EpubLanguage = "epub.language";
    public const string EpubPublisher = "epub.publisher";
    public const string EpubDate = "epub.date";
    public const string EpubDescription = "epub.description";
    public const string EpubIdentifier = "epub.identifier";
    public const string ArchiveEntry = "entry";
    public const string ArchiveSizeBytes = "sizeBytes";
    public const string ArchiveName = "archive";
    public const string ArchiveLastModifiedUtc = "lastModifiedUtc";
    public const string ArchiveContentRole = "contentRole";
    public const string ArchiveOriginalSource = "originalSource";
    public const string InteractionElements = "interactionElements";
    public const string DataVisuals = "dataVisuals";
    public const string Highlights = "highlights";
    public const string StructuredTables = "structuredTables";
    public const string AiInputTokens = "ai.inputTokens";
    public const string AiOutputTokens = "ai.outputTokens";
    public const string AiTotalTokens = "ai.totalTokens";
    public const string AiCallCount = "ai.callCount";
    public const string AiCallType = "ai.callType";
    public const string AiInputAudioTokens = "ai.input.audioTokens";
    public const string AiInputCachedTokens = "ai.input.cachedTokens";
    public const string AiOutputAudioTokens = "ai.output.audioTokens";
    public const string AiOutputReasoningTokens = "ai.output.reasoningTokens";
    public const string AiOutputAcceptedPredictionTokens = "ai.output.acceptedPredictionTokens";
    public const string AiOutputRejectedPredictionTokens = "ai.output.rejectedPredictionTokens";
    public const string AiCostUsd = "ai.costUsd";
    public const string DocumentTitle = "document.title";
    public const string DocumentTitleHint = "document.titleHint";
    public const string DocumentPages = "document.pages";
    public const string DocumentImages = "document.images";
    public const string DocumentTables = "document.tables";
}

/// <summary>
/// Common metadata value constants.
/// </summary>
public static class MetadataValues
{
    public const string ProviderAzureVideoIndexer = "azure_video_indexer";
    public const string ProviderAwsRekognition = "aws_rekognition";
    public const string ProviderAwsTranscribe = "aws_transcribe";
    public const string ProviderGoogleSpeechToText = "google_speech_to_text";
    public const string ProviderAzureDocumentIntelligence = "azure_document_intelligence";
    public const string ProviderYouTube = "youtube";
}
